<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Attendance Report - Bus {{ $bus->number }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            padding: 0;
        }

        /* Header Styling */
        .header {
            text-align: center;
            font-size: 22px;
            font-weight: bold;
            margin-bottom: 15px;
        }

        .sub-header {
            display: flex;
            justify-content: space-between;
            font-size: 14px;
            margin-bottom: 10px;
        }

        .separator {
            border-bottom: 2px solid #000;
            margin-bottom: 10px;
        }

        /* Table Styling */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 10px;
            text-align: left;
            font-size: 14px;
        }

        th {
            background-color: #007bff;
            color: white;
            text-align: center;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        /* Status Colors */
        .status-present {
            background-color: #d4edda;
            color: #155724;
            font-weight: bold;
            text-align: center;
        }

        .status-absent {
            background-color: #f8d7da;
            color: #721c24;
            font-weight: bold;
            text-align: center;
        }

        /* Footer */
        .footer {
            margin-top: 30px;
            font-size: 14px;
            text-align: center;
            color: #555;
        }
    </style>
</head>

<body>

    <!-- PROJECT NAME -->
    <div class="header">
        Automated Transport Management System (ATMS)
    </div>

    <!-- BUS DETAILS & FACULTY IN-CHARGE INFO -->
    <div class="sub-header flex ">
        <div>
            <strong>Bus Number:</strong> {{ $bus->number }} <br>
            <strong>Route:</strong> {{ $bus->route->route_name ?? 'N/A' }}
        </div>
        <div>
            <strong>Date:</strong> {{ now()->format('d-m-Y') }} <br>
            <strong>Faculty In-Charge:</strong> {{ $bus->facultyIncharge->faculty->user->name ?? 'N/A' }}
        </div>
    </div>

    <!-- SEPARATION LINE -->
    <div class="separator"></div>

    <!-- ATTENDANCE TABLE -->
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Student Name</th>
                <th>Check-in Time</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($bus->students as $student)
                @php
                    $busAttendance = $student->busAttendance ? $student->busAttendance->first() : null;
                    $status = $busAttendance ? $busAttendance->status : 'N/A';
                @endphp
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $student->user->name ?? 'N/A' }}</td>
                    <td>{{ $busAttendance ? \Carbon\Carbon::parse($busAttendance->check_in)->format('h:i A') : 'N/A' }}
                    </td>

                    <td class="{{ $status === 'Present' ? 'status-present' : 'status-absent' }}">
                        {{ $status }}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <!-- FOOTER -->
    <div class="footer">
        <p>Generated on: {{ now()->format('d-m-Y') }}</p>
        <p>Note: This report is auto-generated by ATMS</p>
    </div>

</body>

</html>
