<!DOCTYPE html>
<html>
<head>
    <title>Bus Attendance Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid black; padding: 6px; text-align: left; }
        th { background-color: #f2f2f2; }
    </style>
</head>
<body>
    <h2>Attendance Report - Bus {{ $bus->number }}</h2>
    <p><strong>Date:</strong> {{ $date }}</p>
    <p><strong>Time:</strong> {{ ucfirst($time) }}</p>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Student Name</th>
                <th>Check-in</th>
                <th>Check-out</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($attendance as $record)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $record->student->name }}</td>
                    <td>{{ $record->check_in ?? 'N/A' }}</td>
                    <td>{{ $record->check_out ?? 'N/A' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <p>Generated by ATMS | {{ now()->format('Y-m-d H:i:s') }}</p>
</body>
</html>
